### ISSUE TITLE
display correct coordinates when using "BTEcrop"

### ISSUE THREAD

**Issue by Agrrox** [tossowski/CubicChunksMapViewer#1]
Hello, when using "BTEcrop" the coordinates shown in the bottom right corner are displaying incorrect numbers compare to coordinates of buildings in the Minecraft world. 
![Screen Shot 2022-02-24 at 22 14 02](https://user-images.githubusercontent.com/10901821/155608981-25f5f206-fcf3-4d41-8a9d-29992f216ce5.png)

Is there a way to fix this?

Another suggestion is to rename this function to "CCcrop" because the world format is not unique to BTE but rather what Cubic Chunks mod brings. Alternatively to "CubicChunksCrop" to not confuse with "Computer Craft".

**Comment by tossowski** [comment]
I'm not sure if there is an easy way to fix the coordinates because of the way things are drawn on the canvas. It's hard to tell if something just has a really high Y coordinate, or has high X and Z coordinates.

For the renaming, I think your point makes sense. I think right now the way it is implemented is also kind of iffy. If I ever get around to improving it I will change the name.
